export const SET_TOKEN = 'SET_TOKEN'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const SET_TOTAL_BALANCE = 'SET_TOTAL_BALANCE'
export const SET_YEAR_TOTAL = 'SET_YEAR_TOTAL'
export const SET_CURRENT_MONTH_TOTAL = 'SET_CURRENT_MONTH_TOTAL'

export const SET_NEW_CATEGORY = 'SET_NEW_CATEGORY'
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_YEAR_TRANSACTIONS = 'SET_YEAR_TRANSACTIONS'
export const SET_VISIBLE_TRANSACTIONS = 'SET_VISIBLE_TRANSACTIONS'
export const CLEAR_FORM = 'CLEAR_FORM'
export const SET_CATEGORY_TYPE = 'SET_CATEGORY_TYPE'
export const SET_CATEGORY_ICON = 'SET_CATEGORY_ICON'
export const SAVE_CATEGORY_ICON = 'SAVE_CATEGORY_ICON'
export const DELETE_CATEGORY_ICON = 'DELETE_CATEGORY_ICON'

export const SET_CURRENCY_SYMBOL = 'SET_CURRENCY_SYMBOL'

export const SET_FAVORITE_TRANSACTION = 'SET_FAVORITE_TRANSACTION'
export const DELETE_FAVORITE_TRANSACTION = 'DELETE_FAVORITE_TRANSACTION'
export const SET_TRANSACTIONS_SEARCH_VALUE = 'SET_TRANSACTIONS_SEARCH_VALUE'

export const SET_NEW_REMINDER = 'SET_NEW_REMINDER'
export const SET_CHECKED_REMINDER = 'SET_CHECKED_REMINDER'
export const CLEAR_COMPLETED_REMINDERS = 'CLEAR_COMPLETED_REMINDERS'
