export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const SET_TOTAL_BALANCE = 'SET_TOTAL_BALANCE'
export const SET_YEAR_TOTAL = 'SET_YEAR_TOTAL'
export const SET_CURRENT_MONTH_TOTAL = 'SET_CURRENT_MONTH_TOTAL'
