export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const SET_TOTAL_BALANCE = 'SET_TOTAL_BALANCE'
export const SET_YEAR_TOTAL = 'SET_YEAR_TOTAL'
export const SET_CURRENT_MONTH_TOTAL = 'SET_CURRENT_MONTH_TOTAL'

export const SET_NEW_CATEGORY = 'SET_NEW_CATEGORY'
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_YEAR_TRANSACTIONS = 'SET_YEAR_TRANSACTIONS'
export const CLEAR_FORM = 'CLEAR_FORM'
export const SET_CATEGORY_TYPE = 'SET_CATEGORY_TYPE'

export const SET_CURRENCY_SYMBOL = 'SET_CURRENCY_SYMBOL'

export const SET_FAVORITE_TRANSACTIONS = 'SET_FAVORITE_TRANSACTIONS'
